spring:
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:D:\tmp
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
#  security:
#    user:
#      name: admin
#      password: qwer1234
#      roles: ADMIN
logging:
  config: classpath:log4j2.xml
debug: false
#server:
#  error:
#    path: "/404"
---
# debug
spring:
  config:
    activate:
      on-profile: debug
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=sarangbang;trustServerCertificate=true;encrypt=true;
    username: sa
    password: rudnf12dnjf
server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 300m
file:
  path: classpath:/templates
  refPath: classpath:/static
  resourceUri: /fileUpload/**
  resourceLocation: D:/fileUpload/

---
# mysql (mariadb)
spring:
  config:
    activate:
      on-profile: mysql
  jpa:
    database-platform: ??
  datasource:
    url: ??
    username: sa
    password: rudnf12dnjf
server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 30m
---
# mssql
spring:
  config:
    activate:
      on-profile: mssql
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=sarangbang;trustServerCertificate=true;encrypt=true;
    username: sa
    password: rudnf12dnjf
server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 30m